### ISSUE TITLE
Support for 1.20.4

### ISSUE THREAD

**Issue by Yerolopolo** [GameduJS/EasyVillagerTrade#14]
I've been using this mod a lot on 1.19.4 and it would be nice if it was compatible with 1.20.4. Thanks!!

**Comment by GameduJS** [comment]
Hello, 
I've updated to version [1.20.2 - 1.20.4].
You can download it via [ModRinth](https://modrinth.com/mod/easyvillagertrade/version/1.2-1.20.4)

**Comment by Yerolopolo** [comment]
Could you make a release? I cant use it :/

**Comment by GameduJS** [comment]
There you go @Yerolopolo 
[Release 1.20.4](https://github.com/GameduJS/EasyVillagerTrade/releases/tag/v1-20-4)

**Comment by Yerolopolo** [comment]
Thanks!!
