### ISSUE TITLE
Add wildcard for level

### ISSUE THREAD

**Issue by Lau5er** [GameduJS/EasyVillagerTrade#17]
**Is your feature request related to a problem? Please describe.**
For example, I want a power book. Cause i can craft them together i dont care if its a level 2 or 4 etc.
With a wildcarf for exampla a *, I would not have to add all 5 levels.

**Describe the solution you'd like**
I want to put an * for the level and any level with the selected enchantment will be searched for.

**Comment by GameduJS** [comment]
Hello, 
I might add this in the next update. I don't have the time at the moment.

**Comment by GameduJS** [comment]
Completed with latest update
