### ISSUE TITLE
Automatically lock trade once query matching trade is found

### ISSUE THREAD

**Issue by Faervan** [GameduJS/EasyVillagerTrade#18]
**Is your feature request related to a problem? Please describe.**
When staying afk to wait for a right trade to come, one might miss the trade after a query matching one has been found.

**Describe the solution you'd like**
Auto buy one book instantly to lock the trade.

**Comment by GameduJS** [comment]
Hello @Faervan,
this function is already integrated. Make sure you have enough books and emeralds in your inventory.
Or are you using an outdated version?

**Comment by Faervan** [comment]
> Hello @Faervan, this function is already integrated. Make sure you have enough books and emeralds in your inventory. Or are you using an outdated version?

I use 1.2.1 from Modrinth, downloaded at the 29th of July. I had enough items in my inventory.

**Comment by GameduJS** [comment]
I've never encountered this problem before.
Are you playing in multiplayer?
Can you record a video?

**Comment by Faervan** [comment]
... I tried it again (while recording) and it worked...
I'm probably just very dumb, but I was really sure it didn't work before...
(Same server, fewer paper plugins and different settings (I enabled game bugs like duping)
Anyway, sorry for bothering...

**Comment by GameduJS** [comment]
All good, I'm glad it's working
