### ISSUE TITLE
Support for 1.20.5

### ISSUE THREAD

**Issue by Yerolopolo** [GameduJS/EasyVillagerTrade#19]
Hey, could you add support for version 1.20.5? It would be very nice, thanks!

**Comment by GameduJS** [comment]
Here is the Modrinth link: https://modrinth.com/mod/easyvillagertrade/version/1.2.2-1.20.6

I am going to make a release too.

**Comment by GameduJS** [comment]
Nvm just uploading it here:

[EasyVillagerTrade-1.2-1.20.6.zip](https://github.com/user-attachments/files/16468705/EasyVillagerTrade-1.2-1.20.6.zip)
This one is for 1.20.5 and 1.20.6

**Comment by Yerolopolo** [comment]
Thanks as always bro :)
