### ISSUE TITLE
Crashes when using it

### ISSUE THREAD

**Issue by NattoRiisa** [GameduJS/EasyVillagerTrade#20]
Possible mod conflict? Can check with modlist written down

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-08-09 20:34:22
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1646.method_7231()" because the return value of "de.gamedude.easyvillagertrade.core.SelectionInterface.getVillager()" is null
	at de.gamedude.easyvillagertrade.core.EasyVillagerTradeBase.handle(EasyVillagerTradeBase.java:79)
	at de.gamedude.easyvillagertrade.EasyVillagerTrade.lambda$registerCallbacks$2(EasyVillagerTrade.java:64)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$bob000$fabric-lifecycle-events-v1$onStartTick(class_310.java:12678)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1654715416 bytes (1578 MiB) / 3154116608 bytes (3008 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21914.4000
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 29053.18
	Virtual memory used (MiB): 21481.72
	Swap memory total (MiB): 13312.00
	Swap memory used (MiB): 1410.81
	Space in storage for jna.tmpdir (MiB): available: 7358.14, total: 476937.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 7358.14, total: 476937.00
	Space in storage for io.netty.native.workdir (MiB): available: 7358.14, total: 476937.00
	Space in storage for java.io.tmpdir (MiB): available: 18117.39, total: 244081.31
	Space in storage for workdir (MiB): available: 7358.14, total: 476937.00
	JVM Flags: 10 total; -Xmx5120M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		accessories: Accessories 1.0.0-beta.26+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		achiopt: AchievementOptimizer 1.21-1.1.0
		animatica: Animatica 0.6.1+1.21
		architectury: Architectury 13.0.6
		armorchroma: Armor Chroma 1.2.8
		asahi: Asahi 1.1.0+1.20.4
		autotools: AutoTools 2.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		azurelib: AzureLib 2.3.15
		badoptimizations: BadOptimizations 2.1.4
		better_climbing: Better Climbing 3
		better_impaling: Better Impaling 3.0
		betterf3: BetterF3 11.0.1
		betterpingdisplay: Better Ping Display 1.1.1
		blackbarconcealer: Black Bar Concealer 1.0.0
		blahaj: Blåhaj 2.0.0
		blastingraw: BlastingRaw 1.21.1-2-fabric
		brb: Better Recipe Book 1.10.0-rc5+1.21
		buffedsculkcatalysts: Buffed Sculk Catalysts 1.0.1
		calcmod: CalcMod 1.3.2+fabric.1.21
			clientarguments: clientarguments 1.9
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		capes: Capes 1.5.4+1.21
		chat_heads: Chat Heads 0.12.10
		chatanimation: ChatAnimation 1.0.6
		chatpatches: Chat Patches 210.6.5.1
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.81
		continuity: Continuity 3.0.0-beta.5+1.21
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.7
		creativecore: CreativeCore 2.12.6
			net_neoforged_bus: bus 7.2.0
		cubes-without-borders: Cubes Without Borders 2.1.1+1.21
		cull-less-leaves: Cull Less Leaves 1.3.0
		dark-sky: Dark Sky 1.1.2
		darkenchanting: Dark Enchanting 1.3.0+1.21
			omegaconfig: Omega Config Architectury 1.5.1
		deuf_refabricated: DEUF Refabricated 1.1.0
		diamondrails: Diamond Rails 1.0.0
		dynamic_fps: Dynamic FPS 3.6.3
			net_lostluma_battery: battery 1.1.0
		ears: Ears 1.4.6
		easyvillagertrade: EasyVillagerTrade 1.2.1-1.21
		eg_fix_horizontal_camera_lag: Fix Horizontal Camera Lag 1.0.1
		elytra_trinket: Elytra Trinket 1.0.9
		emi: EMI 1.1.10+1.21+fabric
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.21
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.1.3
		entity_sound_features: Entity Sound Features 0.4
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.8
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.10
		expanded_bow_enchanting: Expanded Bow Enchanting 1.1.1
		expanded_crossbow_enchanting: Expanded Crossbow Enchanting 1.0.1
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.10
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.1.0
		expandedstorage: Expanded Storage 14.0.2
		fabric-api: Fabric API 0.100.8+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.13+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.26+a5d66753d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.83+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.0+kotlin.2.0.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		falling-block-particles: Falling Block Particles 1.0.2
		fallingtree: FallingTree 1.21.0.7
		fastquit: FastQuit 3.0.0+1.20.6
		fasttrading: Fast Trading 0.1.5+1.21
		ferritecore: FerriteCore 7.0.0
		feytweaks: FeyTweaks 1.21-1.2.8
			midnightlib: MidnightLib 1.5.7
		fishingrodfix: Fishing rod fix 1.21-0.3
		fishnostuck: Fish No Stuck 1.0.3
		fix-keyboard-on-linux: Fix Keyboard on Linux 1.0.1
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fsb-interop: FabricSkyBoxes Interop 1.4.0+mc1.21-build.54
		fzzy_config: Fzzy Config 0.3.5+1.21
			blue_endless_jankson: jankson 1.2.3
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		galvanizedveneers: GalvanizedVeneers 1.2.0
		guarding: Guarding 1.21.1-2.7.1
		horizontal_glass_panes: Horizontal Glass Panes 3.0.0
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.34+mc1.21
		infinite-music: Infinite Music 0.4.3
		infinitetrading: Infinite Trading 4.5
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		ironbookshelves: Iron Bookshelves 1.21-1.3.4-fabric
			configlibtxf: ConfigLib TXF 7.2.1-fabric
		iseelava: I See Lava 1.0.1
		jade: Jade 15.1.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		languagereload: Language Reload 1.6.1+1.21
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		lithium: Lithium 0.12.7
		long_books: Long Books 1.0
		macos_input_fixes: MacOS Input Fixes 1.7
		mc229142fix: MC229142Fix 1.0
		mc264204fix: MC264204Fix 1.0
		mcwbridges: Macaw's Bridges 3.0.0
		mcwdoors: Macaw's Doors 1.1.1
		mcwfences: Macaw's Fences and Walls 1.1.2
		mcwfurnitures: Macaw's Furniture 3.3.0
		mcwlights: Macaw's Lights and Lamps 1.1.1
		mcwroofs: Macaw's Roofs 2.3.1
		mcwtrpdoors: Macaw's Trapdoors 1.1.3
		mcwwindows: Macaw's Windows 2.3.2
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.0+mc1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		monolib: MonoLib 1.3.0
		moremcmeta: MoreMcmeta 1.21-4.4.7
			moremcmeta_animation_plugin: MoreMcmeta Animation Plugin 1.21-1.0.3
			moremcmeta_gui_plugin: MoreMcmeta GUI Plugin 1.21-1.0.1
			moremcmeta_json_parser_plugin: MoreMcmeta JSON Parser Plugin 1.21-1.1.1
			moremcmeta_properties_parser_plugin: MoreMcmeta Properties Parser Plugin 1.21-1.1.5
			moremcmeta_texture_plugin: MoreMcmeta Texture Plugin 1.21-1.0.1
		moremcmeta_emissive_plugin: MoreMcmeta Emissive Textures Plugin 1.21-2.0.5
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
		movingelevators: Moving Elevators 1.4.7
		mr_beyondenchant: BeyondEnchant 1.5.0
		mr_blasting_plus: Blasting Plus 1.3
		mr_craft_spawneggs: Craft Spawn Eggs 1-v.2.1.3
		mr_enchantments_encore: Enchantments Encore 1.7a
		mr_mine_treasure: Mine Treasure 1.4.6
		mr_miners_delight: Miner's Delight! 3
		mr_neoenchant: Neo Enchant+ 5.6.0
		mr_rmes_campfireleather: RME's Campfire Leather 1.1.5
		mru: Mineblock's Repeated Utilities 0.4.4+1.21
		nemos-ambience: Nemos Ambience 1.1.1-1.21
		nemos-better-mending: Nemo's Better Mending 1.1.1-1.21
		nemos-farming: Nemo's Farming Snapshot-24w32a-1.21
		nemos-woodcutter: Nemo's Woodcutter 1.11.3-1.21
		noisium: Noisium 2.2.1+mc1.21
		notenoughcrashes: Not Enough Crashes 4.4.7+1.21
		nvidium: Nvidium 0.2.9-beta
		obsidianui: ObsidianUI 0.2.7+mc1.21
		onlyhammersandexcavators: OnlyHammersAndExcavators 1.21-0.3
		optigui: OptiGUI 2.3.0-beta.2+1.21
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		particle_core: Particle Core 0.2.4+1.21
			conditional-mixin: conditional mixin 0.5.1
		particlerain: Particle Rain 2.1.2
		polytone: Polytone 1.21-2.2.13
			net_objecthunter_exp4j: exp4j 0.4.8
		puzzle: Puzzle 1.6.3+1.21
			puzzle-base: Puzzle Base 1.6.3+1.21
			puzzle-gui: Puzzle GUI 1.6.3+1.21
			puzzle-models: Puzzle Models 1.6.3+1.21
			puzzle-splashscreen: Puzzle Splash Screen 1.6.3+1.21
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		rendertweaks: Render Tweaks 1.1.0
		reputation: Your Reputation 0.2.7+jade.1.21
		ryoamiclights: RyoamicLights 0.2.9+mc1.21
		shutter: Shutter 1.1
		sketch: Sketch 1.21.1-1.2.1
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.6
		sounds: Sounds 1.1.3+1.21
		status-effect-bars: Status Effect Bars 1.0.6
		stutterfix: StutterFix mc1.21-0.2.3
		superbettergrass: SuperBetterGrass 1.5.3+1.21
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		tclayer: Accessories Trinkets Compat Layer 3.10.0+beta.5
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		template-mod: Iron Ladders 2.2.3
		threadtweak: ThreadTweak 0.1.4+mc1.21
		tiered: Reforged 1.0.2
		timestacker: TimeStacker 1.1.4
		unionlib: UnionLib 12.0.4
		vanillafix: VanillaIcecreamFix 1.2.2-beta
		waterframes: WaterFrames 2.0.14a
		watermedia: WaterMedia 2.0.69
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
	Loaded Shaderpack: (off)
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: EasyVillagerTrade (easyvillagertrade), Minecraft (minecraft), Fabric Loader (fabricloader), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1)

**Comment by NattoRiisa** [comment]
ONLY happens when /evt execute is triggered after breaking a lectern!

**Comment by GameduJS** [comment]
Hello,
It seems like you have not selected the villager.
With the latest version [1.2.3](https://modrinth.com/mod/easyvillagertrade/version/1.2.3-1.21), the mod prevents you from starting if the villager and the lectern are not selected.
